# This file was generated by GoReleaser. DO NOT EDIT.
cask "chronos" do
  name "chronos"
  desc "Convert decimal hours to HH:MM format in CSV and XLSX files"
  homepage "https://github.com/nconklindev/chronos"
  version "1.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chronos"

  on_macos do
    on_intel do
      url "https://github.com/nconklindev/chronos/releases/download/v#{version}/chronos_Darwin_x86_64.tar.gz"
      sha256 "327e183c680d8e111013b14d9ef99bf01b76742bd80abfc4ed9889664f0faef5"
    end
    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the chronos
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nconklindev/chronos/releases/download/v#{version}/chronos_Linux_x86_64.tar.gz"
      sha256 "5ad408318753677d2f83bed6f807bfe82497ea6f41abda80a54ca5cd09140e95"
    end
  end

  # No zap stanza required
end
