# This file was generated by GoReleaser. DO NOT EDIT.
cask "chronos" do
  name "chronos"
  desc "Convert decimal hours to HH:MM format in CSV and XLSX files"
  homepage "https://github.com/nconklindev/chronos"
  version "1.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chronos"

  on_macos do
    on_intel do
      url "https://github.com/nconklindev/chronos/releases/download/v#{version}/chronos_Darwin_x86_64.tar.gz"
      sha256 "ed9421ee6998458740691b6f61105b06655803133dacd8a7bfb9ba34eed5e8eb"
    end
    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the chronos
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nconklindev/chronos/releases/download/v#{version}/chronos_Linux_x86_64.tar.gz"
      sha256 "5000f6db693ce85cbf60c34c453d198f8def56178cb333c93ad31482ddc54101"
    end
  end

  # No zap stanza required
end
