# This file was generated by GoReleaser. DO NOT EDIT.
cask "chronos" do
  name "chronos"
  desc "Convert decimal hours to HH:MM format in CSV and XLSX files"
  homepage "https://github.com/nconklindev/chronos"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chronos"

  on_macos do
    on_intel do
      url "https://github.com/nconklindev/chronos/releases/download/v#{version}/chronos_Darwin_x86_64.tar.gz"
      sha256 "6ada0c7d13732eb4e310a704224e3ab2c9a1b29fa5808bb96f3b9f3bdadf1d29"
    end
    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the chronos
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nconklindev/chronos/releases/download/v#{version}/chronos_Linux_x86_64.tar.gz"
      sha256 "3814fdf270028b5203b87fcd81c67b138bbb4392a400c74ac6956f0d526b9d06"
    end
  end

  # No zap stanza required
end
